baseURL: https://jomal-portfolio.netlify.app
languageCode: en-us
title: Jomal Jochan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Analytics | Startups | Strategy
    title: Jomal Jochan
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 144, Huddleston Road
        title: IQ Tufnell House
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jjochan.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7767979489
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/JochanJomal
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/jomal.jochan
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/the_lowkey_joke
      - icon: fa-github
        label: GitHub
        url: https://github.com/jomaljochan
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jomaljochan
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: A portfolio of my life & work
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: IMG_01.jpg
        subtitle: A journey into my life
        title: About me
        url: blogs/about_me
      - image: IMG_02.jpeg
        subtitle: A peek into my work
        title: Careers & professional life
        url: blogs/career
      - image: GDP_02.png
        subtitle: GDP calculation & variation
        title: A look at GDP of US,India & Germany across the years
        url: blogs/gdp
      - image: pic04.jpg
        subtitle: Stock Analysis
        title: Risk-Return of DJIA stocks
        url: blogs/risk_return
      - image: pic05.jpg
        subtitle: Youth obesity risks
        title: Relationship between weight and physical activity level
        url: blogs/weight_phys
      - image: pic06.jpg
        subtitle: Download
        title: My Resume
        url: "blogs/Jomal_resume.pdf"
  two:
    buttonText: Let's take off!
    enable: yes
    subtitle: "From my first internship at Udaan.com, a growing B2B e-comerce firm in
    India, I have been in love with Analytics. \n Post my move to RBL Bank, a growing
    private sector bank, I have enjoyed using analytics to drive decision making in
    the micro-finance banking sector. \n From the drive to do more and gain an
    international view of the work I do, I have taken up the Masters in Analytics &
    Management degree at London Business School. \n Through the testing courses and
    a cohort of brilliant peers, I wish to venture into the world of Venture Architecture;
    helping firms build businesses from scratch. \n I hope you are part of my journey too!"
    title: My goals
    url: blogs
