---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-09-30"
description: My career # the title that will show up once someone gets to this page
draft: false
image:
keywords: ""
slug: career # slug is the shorthand URL address... no spaces plz
title: My career
---




```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

## Professional goals

Being an engineer who chose to follow a career centered around analytics & leadership, the roles I took up reflected my passion for data and effective decision making driven by data. During my 2 year's of work experience, I worked for a growing B2B e-commerce start-up(Udaan.com) as a Financial Planning & Analysis Intern and an Indian Private Bank(RBL Bank) as Manager-Analytics.

As my career progressed, I was entrusted with more autonomy over my projects & the opportunity to lead and mentor my juniors. This experience is what motivated me to join the **Masters in Analytics & Management Program** at **London Business School**; to be able to lead innovation in data-focused decision making and help firms push forward towards a data- driven society we all will live in in the near future.


## Udaan.com

My first 6 month internship at **Udaan.com**, a growing B2B start-up which was also the fastest unicorn start-up as a **Financial Planning & Analysis Intern** in India was extremely formative as it was the first time I was exposed to Analytics(SQL & R) for business intelligence & financial planning.

As I had no prior experience in analytics, the learning curve was quite steep. Nevertheless, I rose to the opportunity & picked up the skills required for the fast paced environment & began planning the budgets & target planning for one of the largest departments at the firm. This also helped me get selected for projects involving multiple departments requiring high levels of collaboration. These projects 


## RBL Bank

Post my stint at Udaan.com, I shifted to a growing private bank in India: **RBL Bank** as **Manager-Analytics**. With the fairly non-hierarchical leadership team at RBL bank, I was able to prove my ability as a leader as well as an analytics professional. Leading multiple projects involving financial modelling and prediction algorithms, I was able to polish my technical know-how along with tackling the problems of cross-functional team management, project management etc.

This led me to the Masters in Analytics & Management Program at London Business School and I wish to take my experience further by working in Venture Architecture, building businesses from scratch driven my data.









